### ISSUE TITLE
Add a terminal version of TwistPatch 

### ISSUE THREAD

**Issue by vivian-ng** [FlameKat53/Twister-OS-Patcher#7]
@FlameKat53 Thank you for the hard work to make it easy to update Twister OS.

I believe an older version of `twistpatch` used to run fully in the console without the GUI. Is there any way to set an additional option to run without the GUI? I usually use SSH to update my Pi4 remotely. While X forwarding does allow the GUI to pipe through over SSH, it is more convenient if everything was console-based like what it used to be like.

Maybe
`twistpatch`
to run the GUI version, and
`twistpatch --nogui`
to run the console version.

Please consider, thank you!

**Comment by FlameKat53** [comment]
I have no idea how to add the arguments, would "0 or 1" be fine to disable or enable the GUI?

**Comment by FlameKat53** [comment]
figured it out, disregard!

**Comment by FlameKat53** [comment]
Done!

**Comment by mobilegmYT** [comment]
Fixed with 02b74048434c1343b51f6a7bb26a15c2f6e584e2

**Comment by vivian-ng** [comment]
Thanks for adding the `nogui` option. It kind of works, except I think for this line in `checkversion.py` under `def other()` which spawns a terminal window.
```os.system('xfce4-terminal -e ./*patchinstall.sh')```
I have SSH X forwarding so it will spawn a window on my side, I don't know what will happen though if the window fails to spawn if X forwarding is not enable.
