### ISSUE TITLE
Patcher says 'No connection' on Wifi connection.

### ISSUE THREAD

**Issue by wanderling** [FlameKat53/Twister-OS-Patcher#8]
I am, if fact writing this issue on the pi in question using the internet the patcher claims I don't have... Is there a way to bypass this?

Raspberry pi 4 4Gb.

`-Version-
Kernel		: Linux 5.4.51-v8+ (aarch64)
Version		: #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020
C Library		: GNU C Library / (Debian GLIBC 2.28-10+rpi1) 2.28
Distribution		: Raspbian GNU/Linux 10 (buster)
-Current Session-
Computer Name		: raspberrypi
User Name		: pi (pi)
Language		: en_US.UTF-8 (en_US.UTF-8)
Home Directory		: /home/pi
-Misc-
Uptime		: 10 minutes
Load Average		: 0.06, 0.50, 0.39
Available entropy in /dev/random		: 3253 bits (healthy)
`

**Comment by wanderling** [comment]
FYI. I have returned to aarch32 and rebooted with the same results.

**Comment by mobilegmYT** [comment]
1 sec. I'll go take a look at the code since it's been a while since I coded it.

**Comment by mobilegmYT** [comment]
@wanderling Can you go into the terminal and type `twistpatch --nogui`?

**Comment by mobilegmYT** [comment]
Ok, go into ~/patcher/src/update.py, and remove all of this code at the end of the file
`def check_online():
	url = "https://raw.githubusercontent.com/FlameKat53/Twister-OS-Patcher/master/src/resources.py"
	if is_connected("1.1.1.1"):
		print("Network is connected")
		return True
	else:
		print("Network is disconnected")
		return False`

**Comment by wanderling** [comment]
Thanks! That did the trick. Thanks for being awesome!

**Comment by mobilegmYT** [comment]
No problem!
